apiVersion: v1
kind: Pod
metadata:
  name: conmap-demo-2
spec:
  containers:
    - name: demo2
      image: nginx:alpine
      volumeMounts:
        - name: config-volume
          mountPath: /tmp

  volumes:
  - name: config-volume
    configMap:
      name: my-cm-2