apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding

subjects:
- kind: User
  name: admin-user
  apiGroup: rbac.authorization.k8s.io

subjects:
- kind: User
  name: jayesh
  apiGroup: rbac.authorization.k8s.io

roleRef:
  kind: ClusterRole
  name: admin-cluster-role
  apiGroup: rbac.authorization.k8s.io