apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: dev
spec:
  containers:
    - name: demo
      image: nginx
      resources:
        requests:
          memory: "10Mi"
          cpu: "20m"
        limits:
          memory: "256Mi" 
          cpu: "200m"
#error cause max cpu in LimitRange= 200Mi but here we mentioned limit cpu=300Mi o we will get error
# by this example we can know how limit range work