apiVersion: v1
kind: Pod
metadata:
  name: web-new
  namespace: dev
spec:
  containers:
    - name: demo
      image: nginx
      resources:
        requests:
          memory: "20Mi"
          cpu: "20m"
        limits:
          memory: "256Mi" 
          cpu: "200m"

# we will get error cause we are not obeying min rules 
#minimum cpu usage per Container is 100m, but request is 20m, minimum memory usage per Container is 200Mi, but request is 20Mi