apiVersion: v1
kind: Pod
metadata:
  name: cm-vol-1

spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: config-volume  #name of the volume
      mountPath: "/tmp/jayesh" #If the path doesn’t exist in the container’s filesystem, it will create the directory structure for you.
  volumes:
  - name: config-volume  #name of the volume
    configMap:   #similar to emptyDir, hostPath etc (just a volume type)
      name: vol-cm  #name of the configMap