apiVersion: v1
kind: Pod
metadata:
  name: emtdir
spec:
  containers:
    - image: nginx:1.20
      name: test-container
      volumeMounts:
        - name: emtdir
          mountPath: /usr/share/nginx/html
  volumes:
  - name: emtdir
    emptyDir: {}