apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-1
      image: nginx:1.14
      volumeMounts:
        - name: mydata    # both containers use the same volume for data sharing
          mountPath: /data  
    - name: redis-db
      image: redis  # both using nginx so might be port conflict if using same image use different port
    #ports:
    #  - containerPort: 85  # like this differentiate between ports
    
      volumeMounts:
        - name: mydata   # both containers use the same volume for data sharing
          mountPath: /data
  volumes:
    - name: mydata     # name of the volume
      emptyDir: {}