apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
  labels:
    app: myapp
spec:
  containers:
    - name: myapp-container
      image: nginx:1.20
      volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html   # mount path in the container

  volumes:
    - name: nginx-volume
      hostPath: 
         path: /tmp/mynginxdata/ # path on the host in minikube (open using minikube ssh)
         